package printer

import "github.com/mcombeau/go-dns-tools/dns"

type DNSType uint16

var dnsTypeNames = map[uint16]string{
	dns.A:          "A",
	dns.NS:         "NS",
	dns.MD:         "MD",
	dns.MF:         "MF",
	dns.CNAME:      "CNAME",
	dns.SOA:        "SOA",
	dns.MB:         "MB",
	dns.MG:         "MG",
	dns.MR:         "MR",
	dns.NULL:       "NULL",
	dns.WKS:        "WKS",
	dns.PTR:        "PTR",
	dns.HINFO:      "HINFO",
	dns.MINFO:      "MINFO",
	dns.MX:         "MX",
	dns.TXT:        "TXT",
	dns.RP:         "RP",
	dns.AFSDB:      "AFSDB",
	dns.X25:        "X25",
	dns.ISDN:       "ISDN",
	dns.RT:         "RT",
	dns.NSAP:       "NSAP",
	dns.NSAPPTR:    "NSAPPTR",
	dns.SIG:        "SIG",
	dns.KEY:        "KEY",
	dns.PX:         "PX",
	dns.GPOS:       "GPOS",
	dns.AAAA:       "AAAA",
	dns.LOC:        "LOC",
	dns.NXT:        "NXT",
	dns.EID:        "EID",
	dns.NIMLOC:     "NIMLOC",
	dns.SRV:        "SRV",
	dns.ATMA:       "ATMA",
	dns.NAPTR:      "NAPTR",
	dns.KX:         "KX",
	dns.CERT:       "CERT",
	dns.A6:         "A6",
	dns.DNAME:      "DNAME",
	dns.SINK:       "SINK",
	dns.OPT:        "OPT",
	dns.APL:        "APL",
	dns.DS:         "DS",
	dns.SSHFP:      "SSHFP",
	dns.IPSECKEY:   "IPSECKEY",
	dns.RRSIG:      "RRSIG",
	dns.NSEC:       "NSEC",
	dns.DNSKEY:     "DNSKEY",
	dns.DHCID:      "DHCID",
	dns.NSEC3:      "NSEC3",
	dns.NSEC3PARAM: "NSEC3PARAM",
	dns.TLSA:       "TLSA",
	dns.SMIMEA:     "SMIMEA",
	dns.HIP:        "HIP",
	dns.NINFO:      "NINFO",
	dns.RKEY:       "RKEY",
	dns.TALINK:     "TALINK",
	dns.CDS:        "CDS",
	dns.CDNSKEY:    "CDNSKEY",
	dns.OPENPGPKEY: "OPENPGPKEY",
	dns.CSYNC:      "CSYNC",
	dns.ZONEMD:     "ZONEMD",
	dns.SVCB:       "SVCB",
	dns.HTTPS:      "HTTPS",
	dns.SPF:        "SPF",
	dns.UINFO:      "UINFO",
	dns.UID:        "UID",
	dns.GID:        "GID",
	dns.UNSPEC:     "UNSPEC",
	dns.NID:        "NID",
	dns.L32:        "L32",
	dns.L64:        "L64",
	dns.LP:         "LP",
	dns.EUI48:      "EUI48",
	dns.EUI64:      "EUI64",
	dns.TKEY:       "TKEY",
	dns.TSIG:       "TSIG",
	dns.IXFR:       "IXFR",
	dns.AXFR:       "AXFR",
	dns.MAILB:      "MAILB",
	dns.MAILA:      "MAILA",
	dns.ALL:        "*",
	dns.URI:        "URI",
	dns.CAA:        "CAA",
	dns.AVC:        "AVC",
	dns.DOA:        "DOA",
	dns.AMTRELAY:   "AMTRELAY",
	dns.RESINFO:    "RESINFO",
	dns.WALLET:     "WALLET",
	dns.TA:         "TA",
	dns.DLV:        "DLV",
}

func (t DNSType) String() string {
	if n, ok := dnsTypeNames[uint16(t)]; ok {
		return n
	}
	return "Unknown"
}
